package snake;

import java.awt.Label;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author alu20924612v
 */
public class RecordsScore extends javax.swing.JDialog {

    private RecordsScore(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private class Record implements Comparable<Record> {

        public int score;
        public String name;

        public Record(int score, String name) {

            this.score = score;
            this.name = name;

        }

        @Override
        public int compareTo(Record t) {
            if (score > t.score) {
                return 1;

            }

            if (score < t.score) {
                return -1;
            }

            return 0;
        }

    }
    /**
     * Creates new form NewJDialog
     */
    private int score;
    private ArrayList<Record> recordsList;
    private static final String FILE_NAME = "scores.txt";
    private Boolean saveRecord;
    private JLabel[] recordLabels;

    public RecordsScore(java.awt.Frame parent, boolean modal, int score, String player) {
        super(parent, modal);
        this.score = score;
        saveRecord = true;

        initComponents();
        initRecordsLabel();
        jLabelPlayer.setText(player);
        try {
            recordsList = readRecords();
        } catch (IOException ex) {
            Logger.getLogger(RecordsScore.class.getName()).log(Level.SEVERE, null, ex);
        }
        checkCurrentRecord();
    }

    private ArrayList<Record> readRecords() throws IOException {

        ArrayList<Record> list = new ArrayList<Record>();

        BufferedReader input = null;

        try {
            String line;
            int counter = 0;
            input = new BufferedReader(new FileReader(FILE_NAME));
            while ((line = input.readLine()) != null && counter < 5) {

                String[] recordLine = new String[2];
                recordLine = line.split(":");
                Record r = null;
                if (recordLine.length > 1) {
                    r = new Record(Integer.parseInt(recordLine[0]), recordLine[1]);
                    list.add(r);
                    recordLabels[counter].setText(Integer.parseInt(recordLine[0]) + "" + recordLine[1]);
                } else {
                    r = new Record(Integer.parseInt(recordLine[0]), "NONAME");
                    list.add(r);
                    recordLabels[counter].setText(Integer.parseInt(recordLine[0]) + "noname");
                }

                counter++;
            }

        } finally {

            if (input != null) {
                input.close();
            }
        }

        return list;
    }

    private void initRecordsLabel() {

        recordLabels = new JLabel[5];
        recordLabels[0] = jLabelRecord1;
        recordLabels[1] = jLabelRecord2;
        recordLabels[2] = jLabelRecord3;
        recordLabels[3] = jLabelRecord4;
        recordLabels[4] = jLabelRecord5;

    }

    private void checkCurrentRecord() {

        for (Record r : recordsList) {

            if (score < r.score) {

                saveRecord = false;
                break;
            }
        }

        jLabelName.setVisible(saveRecord);
        jTextField.setVisible(saveRecord);
        jLabelCurrentScore.setText("Score: " + score);

    }

    private void saveCurrentRecord(Record r) {

        PrintWriter output = null;
        try {
            recordsList.add(r);
            Collections.sort(recordsList);
            output = new PrintWriter(new FileWriter(FILE_NAME));
            int counter = 0;
            for (Record cr : recordsList) {
                if (counter < 5) {
                    output.println(cr.score + ":" + cr.name);
                    counter++;
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(RecordsScore.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (output != null) {
                output.close();
            }
        }
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCurrentScore = new javax.swing.JLabel();
        jLabelRecord1 = new javax.swing.JLabel();
        jLabelRecord3 = new javax.swing.JLabel();
        jLabelRecord4 = new javax.swing.JLabel();
        jLabelRecord2 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jLabelRecord5 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextField = new javax.swing.JTextField();
        jLabelPlayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCurrentScore.setText("0");

        jLabelRecord1.setText("0 No name");

        jLabelRecord3.setText("0 No name");

        jLabelRecord4.setText("0 No name");

        jLabelRecord2.setText("0 No name");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jLabelRecord5.setText("0 No name");

        jLabelName.setText("Name");

        jTextField.setText(" ");

        jLabelPlayer.setText("Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPlayer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jButtonOK)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelRecord5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCurrentScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPlayer)
                .addGap(10, 10, 10)
                .addComponent(jLabelCurrentScore)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord1)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord2)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord3)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord4)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jLabelName)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        if (saveRecord) {
            Record r = new Record(score, jTextField.getText());
            saveCurrentRecord(r);
        }
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordsScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordsScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordsScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordsScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecordsScore dialog = new RecordsScore(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelCurrentScore;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPlayer;
    private javax.swing.JLabel jLabelRecord1;
    private javax.swing.JLabel jLabelRecord2;
    private javax.swing.JLabel jLabelRecord3;
    private javax.swing.JLabel jLabelRecord4;
    private javax.swing.JLabel jLabelRecord5;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
